require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QueencellsController do

  # This should return the minimal set of attributes required to create a valid
  # Queencell. As you add validations to Queencell, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "age" => "1",
      "box_id" => "1"}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QueencellsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all queencells as @queencells" do
      queencell = Queencell.create! valid_attributes
      get :index, {}, valid_session
      assigns(:queencells).should eq([queencell])
    end
  end

  describe "GET show" do
    it "assigns the requested queencell as @queencell" do
      queencell = Queencell.create! valid_attributes
      get :show, {:id => queencell.to_param}, valid_session
      assigns(:queencell).should eq(queencell)
    end
  end

  describe "GET new" do
    it "assigns a new queencell as @queencell" do
      get :new, {}, valid_session
      assigns(:queencell).should be_a_new(Queencell)
    end
  end

  describe "GET edit" do
    it "assigns the requested queencell as @queencell" do
      queencell = Queencell.create! valid_attributes
      get :edit, {:id => queencell.to_param}, valid_session
      assigns(:queencell).should eq(queencell)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Queencell" do
        expect {
          post :create, {:queencell => valid_attributes}, valid_session
        }.to change(Queencell, :count).by(1)
      end

      it "assigns a newly created queencell as @queencell" do
        post :create, {:queencell => valid_attributes}, valid_session
        assigns(:queencell).should be_a(Queencell)
        assigns(:queencell).should be_persisted
      end

      it "redirects to the created queencell" do
        post :create, {:queencell => valid_attributes}, valid_session
        response.should redirect_to(Queencell.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved queencell as @queencell" do
        # Trigger the behavior that occurs when invalid params are submitted
        Queencell.any_instance.stub(:save).and_return(false)
        post :create, {:queencell => { "age" => "invalid value" }}, valid_session
        assigns(:queencell).should be_a_new(Queencell)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Queencell.any_instance.stub(:save).and_return(false)
        post :create, {:queencell => { "age" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested queencell" do
        queencell = Queencell.create! valid_attributes
        # Assuming there are no other queencells in the database, this
        # specifies that the Queencell created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Queencell.any_instance.should_receive(:update_attributes).with({ "age" => "1" })
        put :update, {:id => queencell.to_param, :queencell => { "age" => "1" }}, valid_session
      end

      it "assigns the requested queencell as @queencell" do
        queencell = Queencell.create! valid_attributes
        put :update, {:id => queencell.to_param, :queencell => valid_attributes}, valid_session
        assigns(:queencell).should eq(queencell)
      end

      it "redirects to the queencell" do
        queencell = Queencell.create! valid_attributes
        put :update, {:id => queencell.to_param, :queencell => valid_attributes}, valid_session
        response.should redirect_to(queencell)
      end
    end

    describe "with invalid params" do
      it "assigns the queencell as @queencell" do
        queencell = Queencell.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Queencell.any_instance.stub(:save).and_return(false)
        put :update, {:id => queencell.to_param, :queencell => { "age" => "invalid value" }}, valid_session
        assigns(:queencell).should eq(queencell)
      end

      it "re-renders the 'edit' template" do
        queencell = Queencell.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Queencell.any_instance.stub(:save).and_return(false)
        put :update, {:id => queencell.to_param, :queencell => { "age" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested queencell" do
      queencell = Queencell.create! valid_attributes
      expect {
        delete :destroy, {:id => queencell.to_param}, valid_session
      }.to change(Queencell, :count).by(-1)
    end

    it "redirects to the queencells list" do
      queencell = Queencell.create! valid_attributes
      delete :destroy, {:id => queencell.to_param}, valid_session
      response.should redirect_to(queencells_url)
    end
  end

end
